### ISSUE TITLE
Elemente für alle drei Ebenen anordnen (gleiches soll wenn möglich an gleicher Stelle sein, wenn das nicht geht, ist das aber auch kein Problem)

### ISSUE THREAD

**Issue by simondueckert** [simondueckert/lernos-core#5]

**Comment by karstenpe** [comment]
hier eine erste Durchgängigkeit --> in diagrams.net öffnen und die Ebenen durchschalten!
https://github.com/karstenpe/lernos-core/blob/master/lernOS%20Canvas/de/Canvas-Stack-meta-FULLSTACK.svg
